#include "../Inc/i2c.h"

#define PE_EN (1<<0)
#define I2C1_EN (1<<21)
#define GPIOB_EN (1<<1)
#define ALT_MODE_EN (2<<12) | (2<<14)
#define OPEN_DRAIN_EN (1<<6) | (1<<7)
#define PIN_SPEED_VH (3<<12) | (3<<14)
#define PULL_UP (1<<12) | (1<<14)
#define ALT_MODE_I2C (4<<24) | (4<<28)
#define I2C_FREQ (0x307075B1U) 				//100kHz generated by STM32CubeMX tool
#define AUTOEND (1<<25)
#define NBYTES_INIT (0xFFU)
#define ADD10 (1<<11)
#define I2C_START (1<<13)

void I2C1_Config(void){
	I2C1->CR1 &= ~PE_EN; 					//Ensure software reset for I2C1
	RCC->APB1LENR |= I2C1_EN; 				//Peripheral clock enable for I2C1
	RCC->AHB4ENR |= GPIOB_EN; 				//GPIOB clock enable
	GPIOB->MODER |= ALT_MODE_EN; 			//Enable alternate function for PB6 and PB7
	GPIOB->OTYPER |= OPEN_DRAIN_EN; 		//Configure PB6 and PB7 to work as open-drain
	GPIOB->OSPEEDR |= PIN_SPEED_VH; 		//Set output speed of PB6 and PB7 as very high
	//GPIOB->PUPDR |= PULL_UP; 				//Enable pull-up resistors for PB6 and PB7 // is this done externally?
	GPIOB->AFR[0] |= ALT_MODE_I2C; 			//Set alternate function as I2C1 for pins PB6 and PB7 (SCL and SDA)
	I2C1->TIMINGR |= I2C_FREQ; 				//Set I2C speed frequency
	I2C1->CR1 |= PE_EN;	 					//Enable I2C
}

void I2C1_Master_Init(void){
	I2C1->CR2 |= AUTOEND;					//Enable auto-end feature
	I2C1->CR2 |= (NBYTES_INIT << 16);		//Initial condition for amount of bytes to send/read
	I2C1->CR2 &= ~ADD10;					//7-bit addressing mode
}

void I2C1_Master_Write(uint32_t *addr, uint32_t *msg, uint8_t size){
	//I2C1->CR2       SADD
	//I2C1->CR2       RD_WRN
	//I2C1->CR2		  NBYTES
	//I2C1->CR2		  HEAD10R
	//if I2C1->ISR TXE == 1 then I2C1->TXDR TXDATA
	I2C1->CR2 |= I2C_START;
}
